defmodule KumaSanKanji.Repo.Migrations.AddUserKanjiProgress do
  @moduledoc """
  Adds the user_kanji_progress table for SRS functionality.

  This file was autogenerated with `mix ash_sqlite.generate_migrations` and then manually edited.
  """

  use Ecto.Migration

  def up do
    create table(:user_kanji_progress, primary_key: false) do
      add :kanji_id,
          references(:kanjis, column: :id, name: "user_kanji_progress_kanji_id_fkey", type: :uuid),
          null: false

      add :user_id,
          references(:users, column: :id, name: "user_kanji_progress_user_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :correct_reviews, :bigint, null: false
      add :total_reviews, :bigint, null: false
      add :last_reviewed_at, :utc_datetime
      add :first_reviewed_at, :utc_datetime
      add :last_result, :text
      add :repetitions, :bigint, null: false
      add :ease_factor, :decimal, null: false
      add :interval, :bigint, null: false
      add :next_review_date, :utc_datetime, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:user_kanji_progress, [:user_id, :kanji_id],
             name: "user_kanji_progress_unique_user_kanji_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_kanji_progress, [:user_id, :kanji_id],
                     name: "user_kanji_progress_unique_user_kanji_index"
                   )

    drop constraint(:user_kanji_progress, "user_kanji_progress_user_id_fkey")
    drop constraint(:user_kanji_progress, "user_kanji_progress_kanji_id_fkey")
    drop table(:user_kanji_progress)
  end
end