defmodule KumaSanKanji.Repo.Migrations.InitialTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :joined_at, :utc_datetime
      add :username, :text, null: false
      add :hashed_password, :text, null: false
      add :email, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:kanjis, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :jlpt_level, :bigint
      add :stroke_count, :bigint
      add :grade, :bigint
      add :character, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:kanji_pronunciations, primary_key: false) do
      add :kanji_id,
          references(:kanjis,
            column: :id,
            name: "kanji_pronunciations_kanji_id_fkey",
            type: :uuid
          ),
          null: false

      add :romaji, :text
      add :type, :text, null: false
      add :value, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:kanji_meanings, primary_key: false) do
      add :kanji_id,
          references(:kanjis, column: :id, name: "kanji_meanings_kanji_id_fkey", type: :uuid),
          null: false

      add :is_primary, :boolean
      add :language, :text
      add :value, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:kanji_example_sentences, primary_key: false) do
      add :kanji_id,
          references(:kanjis,
            column: :id,
            name: "kanji_example_sentences_kanji_id_fkey",
            type: :uuid
          ),
          null: false

      add :language, :text
      add :translation, :text, null: false
      add :japanese, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:kanji_example_sentences, "kanji_example_sentences_kanji_id_fkey")

    drop table(:kanji_example_sentences)

    drop constraint(:kanji_meanings, "kanji_meanings_kanji_id_fkey")

    drop table(:kanji_meanings)

    drop constraint(:kanji_pronunciations, "kanji_pronunciations_kanji_id_fkey")

    drop table(:kanji_pronunciations)

    drop table(:kanjis)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end